using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using GeometryClassLibrary;
using System.Diagnostics;

namespace GeometryClassLibrary
{

    ///                                                                                                                                                                                                                                                                          
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                               =NMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN8I                                                                                                            
    ///                                                              ~OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM8D                                                                                                           
    ///                                                             ,7MMNOOZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZONMMO                                                                                                          
    ///                                                             ,7MMO                                                                                           ,$MMN,                                                                                                        
    ///                                                             ,7MMO                                                                                             NMMO                                                                                                        
    ///                                                             ,7MMO                                                                                             7MMM,                                                                                                       
    ///                                                             ,7MMO                                                                                             ,OMMD,                                                                                                      
    ///                                                             ,7MMO                                                                                               DMMD                                                                                                      
    ///                                                             ,7MMO                                                                                                MMM8                                                                                                     
    ///                                                             ,7MMO                                                                                                =MMM=                                                                                                    
    ///                                                             ,7MMO                                                                                                 ZMMM7                                                                                                   
    ///                                                             ,7MMO                                                                                                  8MMM                                                                                                   
    ///                                                             ,7MMO                                                                                                   OMMM                                                                                                  
    ///                                                             ,7MMO                                                                                                    NMMD                                                                                                 
    ///                                                             ,IMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM                                                                                                
    ///                                                              ,IMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM7,                                                                                                
    ///                                                               :?+???????????????????????????????????????????????????????????????????????????????????????????????????????~                                                                                                 
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                             ,I                                                                                                                                                            
    ///                                                                                                             MM~                                                                                                                                                           
    ///                                                                                                           ,MMMM=                                                                                                                                                          
    ///                                                                                                          =OMMMMM$                                                                                                                                                         
    ///                                                                                                          NMMN+MMM7                                                                                                                                                        
    ///                                                                                                        ,MMMD, OMMM,                                                                                                                                                       
    ///                                                                                                       ~MMMD    OMMM=                                                                                                                                                      
    ///                                                                                                      :MNMZ~     ?MMM7                                                                                                                                                     
    ///                                                                                                      8MMN,       7MMM~                                                                                                                                                    
    ///                                                                                                     ZMMM=    :   ,MMMD?                                                                                                                                                   
    ///                                                                                                   ,8MMN:   78M    ,DMMN,                                                                                                                                                  
    ///                                                                                                   OMMM:   +MMM+     DMMN,                                                                                                                                                 
    ///                                                                                                 :$MMM~   OMMMMMO,    OMMMO                                                                                                                                                
    ///                                                                                                 OMMM=   IMMMMMMMZ    ~$MMM:                                                                                                                                               
    ///                                                                                                OMMN=  ,$MMMMNIMMMI    ,NMM8:                                                                                                                                              
    ///                                                                                               IMMM~   ZMMMMM: NMMN      NMMN,                                                                                                                                             
    ///                                                                                              OMMMD   +MMMMM,  :MMM8     ~DMMM:                                                                                                                                            
    ///                                                                                             =MMM7   ~MMMMM7    ,MMM?      NMM8                                                                                                                                            
    ///                                                                                            7MMM+   ?MMMMMMI    ,MMMMZ     =MMMZ                                                                                                                                           
    ///                                                                                           DMMM7   $NMM?MMMI    ,MMMMM+     :NMMN                                                                                                                                          
    ///                                                                                          IMMM~   :MMM$:MMMI    :MMMMMMZ      NMMM                                                                                                                                         
    ///                                                                                         =MMM$   +MMMO ,MMMI    :MMMIMMMI     :MMMZ:                                                                                                                                       
    ///                                                                                        7MMM?   IMMNI  :MMMI    :MMM ~MMMZ     +MMM8                                                                                                                                       
    ///                                                                                       OMMM,   IMMM=   :MMMI    ,MMM  $MMMM     ,NMMN                                                                                                                                      
    ///                                                                                       MMMZ   $MMMN    :MMMI    ,MMM   ?MMM+     ,NMM8:                                                                                                                                    
    ///                                                                                     ~DMM8,  :NMMO,    :MMMI    :MMM    ZMMM+     7NMMN                                                                                                                                    
    ///                                                                                    ~NMM8   =NMMO      :MMMI    :MMM     ZMMM?     +MMM+                                                                                                                                   
    ///                                                                                   IMMM=   DMMM7       :MMMI    :MMM       NMMO     :MMMN,                                                                                                                                 
    ///                                                                                  $NMMD   +MNM+        :MMMI    :MMM       $MMM=     ~8MMN                                                                                                                                 
    ///                                                                                 :NMMO:  ~NMMD,        :MMMI    :MMM        ZMMM+     ,MMMZ ,                                                                                                                              
    ///                                                                                ~NMM8 , ~MMMO          :MMMI    :MMM         IMMMI     $MMM~                                                                                                                               
    ///                                                                               ~NMM8   +MMMZ           :MMMI    :MMM          $MMM~     $MMM?                                                                                                                              
    ///                                                                              ,MMM$=   NMM8            :MMMI    :MMM          ,MMMN?     +MMM$                                                                                                                             
    ///                                                                              8MMM   :NMMM:            :MMMI    :MMM           ,8MMN:     ?NMM=                                                                                                                            
    ///                                                                            :MMM8   ~MMMO              :MMMI    :MMM             7MMM?     8MMM$                                                                                                                           
    ///                                                                           ~MMMZ   ~MMM$               :MMMI    ,MMM              8MMNZ     7MMM+                                                                                                                          
    ///                                                                           NMM8   IDMMM                :MMMI    ,MMM               7MMM~     ?NMMI                                                                                                                         
    ///                                                                         ,OMMM:  ,MMMD,                :MMMI    :MMM                8MMM~     OMMM8                                                                                                                        
    ///                                                                        :NMMN,  ~MMMO                  :MMMI    :MMM               ~MMMMMI     IMMM=                                                                                                                       
    ///                                                                        MMM8   ?MMM8                   :MMMI    :MMM              7NMMNMMMI     OMMM=                                                                                                                      
    ///                                                                      ~ZMMM:  ~MMM8+                   :MMMI    :MMM             ,NMM8~DMMN     ,ZMMM?                                                                                                                     
    ///                                                                      NMMD~   NMMMMN?                  :MMMI    :MMM            IMMM7   OMMM=     :MMM7                                                                                                                    
    ///                                                                     NMMD   =MMMO$MMMN+                :MMMI    :MMM           DMMM$     ?MMM$     OMMM:                                                                                                                   
    ///                                                                   =MMMN   ?MMMI  7DMMMI               :MMMI    :MMM          ?MMM+       7MMM+    ,8MMM+                                                                                                                  
    ///                                                                  ,MMM8=   MMM8    :8MMMO~             :MMMI    :MMM         +MMMO       =DMMM8?     7MMM+                                                                                                                 
    ///                                                                  $MMM:  :$MMN:      INMMMI            :MMMI    :MMM        7MMMI       +MMMDMMN,     ZMMM:                                                                                                                
    ///                                                                 ?MMM7   8MMM:         MMMM?           :MMMI    :MMM       ZMMM+       +MMM7 DMMM:    :MMMZ~                                                                                                               
    ///                                                                $MMM=  ,NMMM8,          $MMMM?         :MMMI    ,MMM      ,MMMO        NMMO   NMMD=    ~MMMN                                                                                                               
    ///                                                               ZMMN,  ~OMMMMMMO           OMMM$:       :MMMI    ,MMM     IMMMZ       =MMMN    =OMMM,    ,NMMN                                                                                                              
    ///                                                              +MMN?  ,DMMD+7MMMM?:         ?DMMM$:     :MMMI    :MMM   ,DMMN~       ZMMM?      ,DMMN~     DMMN?                                                                                                            
    ///                                                             IMMM7   8MMM:  :OMMMN,          7MMMD+    :MMMI    ,MMM  ,$MMM~       IMMM+         DMMM:    +8MMM                                                                                                            
    ///                                                            ZMMM~  :MMMN,     ~MMMM$          +8MMMZ   :MMMI    ,MMM  DMMM$       8MMMD          ,ZMMM= ,  ,MMM8                                                                                                           
    ///                                                           IMMM:  ,MMMO+        $MMMM=          7MMMM7 :MMMI    :MMM 8MMM~       7MMMI             MMMN     ,NMMN                                                                                                          
    ///                                                          ZMMMD   8MMM,           NMMMM,         ,7MMMD:MMMI    :MMMNMMN        8MMM,              ,MMMD,    ,OMMM,                                                                                                        
    ///                                                         +MMMI   DMMN,             =MMMM7          IMMMMMMMI    ,MMMMMZ~       MMM8+                 DMMM:     NMMD                                                                                                        
    ///                                                        ?MMMI  :NMMD                :ZMMMN+         ,$MMMMMI    ,MMMMM,,      ZMMM~                  ,8MMM:    =MMM$                                                                                                       
    ///                                                      ,8MMM?   MMMD                    NMMM$          :MMMMI    :MMM8        NMMM:                     MMM8?    ,NMMD                                                                                                      
    ///                                                      ?MMM=  :8MMM:                    ,+NMMNZ          :MMMI    :MMM       +MMM8                       :NMMN,     DMMM,                                                                                                    
    ///                                                     +MMM7  ,NNMN                         7MMM8?       :MMMI    :MMM       MMM8                         ,8MMN~,   ,MMM$=                                                                                                   
    ///                                                    ?MMMI  :NMM8:                          ?NMMM$      :MMMI    :MMM     :DMMN:                           DMMN?    INMM8                                                                                                   
    ///                                                   IMMM?  ~$MMM:                            ,$MMMD?    ,MMMI    ,MMM    ~DMM8:                            +8MMM,    +MMMZ                                                                                                  
    ///                                                   DMMO   8MMM8:::::::::::::::::::::::::::::::$NMMM?:::=MMM$::::=MMM=::~NMMN~~:::::::::::::::::::::::::::::+MMMZ     ~MMM$                                                                                                 
    ///                                                 ,8MMM:  7MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO     OMMMD                                                                                                
    ///                                                ?MNMI  ,$Z$OZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZDDDDDDDDDDDDZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZOZZ,    ~MMM$                                                                                               
    ///                                               =MMM7                                                                                                                    +MMN$                                                                                              
    ///                                              ?8MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM$                                                                                             
    ///                                              NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM$                                                                                            
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                               ,MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN?                                                                                                   
    ///                                                                                                              =MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMD                                                                                                  
    ///                                                                                                              =MMM                                                   =MMN                                                                                                  
    ///                                                                                                              =MMM                                                   =MMN                                                                                                  
    ///                                                                                                              =MMM                                                   =MMN                                                                                                  
    ///                                                                                                              =MMM                                                   =MMN                                                                                                  
    ///                                                                                                              =MMM                                                   +MMN                                                                                                  
    ///                                                                                                              =MMM                                                   +MMN                                                                                                  
    ///                                                                                                              =MMM                                                   +MMN                                                                                                  
    ///                                                                                                              =MMM                                                   +MMN                                                                                                  
    ///                                                                                                              =MMM                                                   ?MMD                                                                                                  
    ///                                                                                                              =MMM                                                   ?MMO                                                                                                  
    ///                                                                                                              ~MMM                                                   ?MMO                                                                                                  
    ///                                                                                                              ~MMM                                                   ?MMO                                                                                                  
    ///                                                                                                              =MMM                                                   +MMO                                                                                                  
    ///                                                                                                              =MMM                                                   IMMO                                                                                                  
    ///                                                                                                              ~MMM                                                   IMMO                                                                                                  
    ///                                                                                                              ~MMM                                                   IMMO                                                                                                  
    ///                                                                                                              =MMM                                                   IMMO                                                                                                  
    ///                                                                                                              =MMM                                                   IMMO                                                                                                  
    ///                                                                                                              =MMM                                                   IMMZ                                                                                                  
    ///                                                                                                              =MMM                                                   IMMZ                                                                                                  
    ///                                                                                                              =MMM                                                   IMM$                                                                                                  
    ///                                                                                                              =MMM                                                   IMM$                                                                                                  
    ///                                                                                                              =MMM                                                   7MM$                                                                                                  
    ///                                                                                                              =MMM                                                   $MM$                                                                                                  
    ///                                                                                                              =MMM                                                   $MM$                                                                                                  
    ///                                                                                                              =MMM                                                   $MM$                                                                                                  
    ///                                                                                                              ~MMM                                                   $MM$                                                                                                  
    ///                                         :MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMM                                                   $MM$                                                                                                  
    ///                                       :MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMN                                                     $MM7                                                                                                  
    ///                                       ~MMM      ZMMI +MMM,  ,7MMO OMM$:   MMM+ MMM7   NMMZ IMM8                                                                     $MM7                                                                                                  
    ///                                       ~MMM      ZMMI +MMM,  ,7MMO OMM$:   MMM+ MMM7   NMMZ IMM8                                                                     $MM7                                                                                                  
    ///                                       ~MMM      ZMMI +MMM,  ,7MMO OMM$:   MMM+ MMM7   NMMZ IMM8                                                                     $MM7                                                                                                  
    ///                                       ~MMM      ZMMI +MMM,  ,7MMO OMM$:   MMM+ MMM7   NMMZ IMM8                                                                     ZMM7                                                                                                  
    ///                                       ~MMM      ZMMI +MMM,  ,7MMO OMM$:   MMM+ MMM7   NMMZ IMM8                                                                     OMM7                                                                                                  
    ///                                       ~MMM      ZMMI +MMM,  ,7MMO OMM$:   MMM+ MMM7   NMMZ IMM8                                                                     OMM7                                                                                                  
    ///                                       ~MMM      ZMMI +MMM,  ,7MMO OMM$:   MMM+ MMM7   NMMZ IMM8                                                                     OMM7                                                                                                  
    ///                                       ~MMM      ZMMI +MMM,  ,7MMO OMM$:   MMM+ MMM7   NMMZ IMM8                                                                     OMM7                                                                                                  
    ///                                       ~MMM      ZMMI +MMM,  ,7MMO OMM$:   MMM+ MMM7   NMMZ IMM8                                                                     OMM?                                                                                                  
    ///                                       ~MMM      ZMMI +MMM,  ,7MMO OMM$:   MMM+ MMM7   NMMZ IMM8                                                                     OMM?                                                                                                  
    ///                                       ~MMM      ZMMI +MMM,  ,7MMO OMM$:   MMM+ MMM7   NMMZ IMM8                                                                     OMM+                                                                                                  
    ///                                       ~MMM      ZMMI +MMM,  ,7MMO OMM$:   MMM+ MMM7   NMMZ IMM8                                                                     OMM+                                                                                                  
    ///                                       ~MMM      ZMMI +MMM,  ,7MMO OMM$:   MMM+ MMM7   NMMZ IMM8                                                                     8MM+                                                                                                  
    ///                                       ~MMM      ZMMI +MMM,  ,7MMO OMM$:   MMM+ MMM7   NMMZ IMM8                                                                     DMM+                                                                                                  
    ///                                       ~MMM      ZMMI +MMM,  ,7MMO OMM$:   MMM+ MMM7   NMMZ IMM8                                                                     DMM+                                                                                                  
    ///                                       ~MMM      ZMMI +MMM,  ,7MMO OMM$:   MMM+ MMM7   NMMZ IMM8                                                                     DMM+                                                                                                  
    ///                                       ~MMM      ZMMI +MMM,  ,7MMO OMM$:   MMM+ MMM7   NMMZ IMM8                                                                     DMM+                                                                                                  
    ///                                       ~MMM      ZMMI +MMM,  ,7MMO OMM$:   MMM+ MMM7   NMMZ IMM8                                                                     DMM+                                                                                                  
    ///                                       ~MMM      ZMMI +MMM,  ,7MMO OMM$:   MMM+ MMM7   NMMZ IMM8                                                                     DMM=                                                                                                  
    ///                                       ~MMM      ZMMI +MMM,  ,7MMO OMM$:   MMM+ MMM7   NMMZ IMM8                                                                     DMM=                                                                                                  
    ///                                       ~MMM      ZMMI +MMM,  ,7MMO OMM$:   MMM+ MMM7   NMMZ IMM8                                                                     DMM~                                                                                                  
    ///                                       ~MMM      ZMMI +MMM,  ,7MMO OMM$:   MMM+ MMM7   NMMZ 7MM8                                                                     DMM~                                                                                                  
    ///                                       ~MMM      ZMMI +MMM,  ,7MMO OMM$:   MMM+ MMM7   NMMZ 7MM8                                                                     MMM~                                                                                                  
    ///                                       ~MMM      ZMMI +MMM,  ,7MMO OMM$:   MMM+ MMM7   NMMZ IMM8                                                                     MMM=                                                                                                  
    ///                                       ~MMM      ZMMI +MMM,  ,7MMO OMM$:   MMM+ MMM7   NMMZ IMM8                                                                     MMM=                                                                                                  
    ///                                       ~MMM      ZMMI +MMM,  ,7MMO OMM$:   MMM+ MMM7   NMMZ IMM8                                                                     MMM~                                                                                                  
    ///                                       ~MMM      ZMMI +MMM,  ,7MMO OMM$:   MMM+ MMM7   NMMZ IMM8                                                                     MMM=                                                                                                  
    ///                                       ~MMM      ZMMI +MMM,  ,7MMO OMM$:   MMM+ MMM7   NMMZ IMM8                                                                     MMM:                                                                                                  
    ///                                       ~MMM      ZMMI +MMM,  ,7MMO OMM$:   MMM+ MMM7   NMMZ IMM8                                                                     MMM:                                                                                                  
    ///                                       ~MMM      ZMMI +MMM,  ,7MMO OMM$:   MMM+ MMM7   NMMZ IMM8                                                                     MMM:                                                                                                  
    ///                                       ~MMM      ZMMI +MMM,  ,7MMO OMM$:   MMM+ MMM7   NMMZ IMM8                                                                     MMM:                                                                                                  
    ///                                       ~MMM      ZMMI +MMM,  ,7MMO OMM$:   MMM+ MMM7   NMMZ IMM8                                                                     MMM:                                                                                                  
    ///                                       ~MMM      ZMMI +MMM,  ,7MMO OMM$:   MMM+ MMM7   NMMZ IMM8                                                                    :MMM:                                                                                                  
    ///                                       ~MMM      ZMMI +MMM,  ,7MMO OMM$:   MMM+ MMM7   NMMZ IMM8                                                                    :MMM,                                                                                                  
    ///                                       ~MMM      ZMMI +MMM,  ,7MMO OMM$:   MMM+ MMM7   NMMZ IMM8                                                                    :MMM,                                                                                                  
    ///                                       ~MMM      ZMMI +MMM,  ,7MMO OMM$:   MMM+ MMM7   NMMZ IMM8                                                                    :MMM:                                                                                                  
    ///                                       ~MMM      ZMMI +MMM,  ,7MMO OMM$:   MMM+ MMM7   NMMZ IMM8                                                                    :MMM                                                                                                   
    ///                                       ~MMM      ZMMI +MMM,  ,7MMO OMM$:   MMM+ MMM7   NMMZ IMM8                                                                    :MMM                                                                                                   
    ///                                       ~MMM      ZMMI +MMM,  ,7MMO OMM$:   MMM+ MMM7   NMMZ IMM8                                                                    :MMM                                                                                                   
    ///                                       ~MMM      ZMMI +MMM,  ,7MMO OMM$:   MMM+ MMM7   NMMZ IMM8                                                                    :MMM                                                                                                   
    ///                                       ~MMM      ZMMI +MMM,  ,7MMO OMM$:   MMM+ MMM7   NMMZ IMM8                                                                    :MMM                                                                                                   
    ///                                       ~MMM      ZMMI +MMM,  ,7MMO OMM$:   MMM+ MMM7   NMMZ IMM8                                                                    ~MMM                                                                                                   
    ///                                       ~MMM      ZMMI +MMM,  ,7MMO OMM$:   MMM+ MMM7   NMMZ IMM8                                                                    =MMM                                                                                                   
    ///                                       ~MMM      OMMI +MMM,  ,IMMO OMM$:   MMM+ MMM7   NMMZ 7MM8                                                                    ~MMM                                                                                                   
    ///                                       ~MMM:~::::OMM$:?MMM~::~$MM8:DMMZ=:::MMMI:MMM$:::MMMO:$MMD:~::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::?MMM                                                                                                   
    ///                                       ~MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM                                                                                                   
    ///                                         :MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM=                                                                                                    
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                    IOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO88DMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMD                                                                                                             
    ///                                                                  :ONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO:                                                                                                           
    ///                                                                  =MMM+~=======================================NMMD=~=======================================NMM=                                                                                                           
    ///                                                                  =MMM:                                        DNMD                                         MMM=                                                                                                           
    ///                                                                  =MMM:                                        DMM8                                         MMM=                                                                                                           
    ///                                                                  =MMM:                                        DMM8                                         MMM=                                                                                                           
    ///                                                                  =MMM:                                        DMMD                                         MMM=                                                                                                           
    ///                                                                  =MMM:                                        DMMD                                         MMM=                                                                                                           
    ///                                                                  =MMM:                                        DMMD                                         MMM=                                                                                                           
    ///                                                                  =MMM:                                        DMMD                                         MMM=                                                                                                           
    ///                                                                  =MMM:                                        NMMD                                         MMM=                                                                                                           
    ///                                                                  =MMM:                                        NMMD                                         MMM=                                                                                                           
    ///                                                                  =MMM:                                        NMMD                                         MMM=                                                                                                           
    ///                                                                  =MMM:                                        NMMD                                         MMM=                                                                                                           
    ///                                                                  =MMM:                                        NMMD                                         MMM=                                                                                                           
    ///                                                                  =MMM:                                        NMMD                                         MMM=                                                                                                           
    ///                                                                  =MMM:                                        NMMD                                         MMM=                                                                                                           
    ///                                                                  =MMM:                                        NMMD                                         MMM=                                                                                                           
    ///                                                                  =MMM:                                        NMMD                                         MMM=                                                                                                           
    ///                                                                  ~MMM:                                        NMMD                                         MMM~                                                                                                           
    ///                                                                  =MMM:                                        NMMD                                         MMM=                                                                                                           
    ///           7MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:                                        NMM8                                         MMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM7,                                                   
    ///          MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM?                                          NMMD                                          ,MMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN?                                                  
    ///          MMM+,,,ZMM7+MMN,,$MMN~MMM7,~8MMI$MM8,~MMM~NMMI,,,,,,,,,,,:                                           NMMD                                           :,,,,,,,,,,,,MMMIMMM=:IMM8,MMM~,IDMM$NMMZ,,ZMMZ+MMM,,,,DMM+                                                  
    ///          MMM~   $MM7~MMN  7MMD,MMMI ,OMM?$MMO :MMM:DMM?                                                       NMMD                                                        MMM+MMM~ ?MM8 MMM: ?8MN7NMM$  $MMZ=MMM    DMM+                                                  
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM+                                                       NMMD                                                        MMM?MMM~ ?MM8 MMM: ?DMNINMM$  $MMZ=MMM    DMM+                                                  
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM+                                                       NMMD                                                        MMM?MMM~ ?MM8 MMM: ?DMNINMM$  $MMZ=MMM    DMM+                                                  
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,8MM+$MMO :MMM,DMM?                                                       NMMD                                                        MMM?MMM~ ?MM8 MMM: ?DMNINMM$  $MMZ=MMM    DMM+                                                  
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,8MM+$MMO :MMM,DMM?                                                       NMMD                                                        MMM?MMM~ ?MM8 MMM: ?DMNINMM$  $MMZ=MMM    DMM+                                                  
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       NMMD                                                        MMM?MMM~ ?MM8 MMM: ?DMNINMM$  $MMZ=MMM    DMM+                                                  
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       NMMN                                                        MMM?MMM~ ?MM8 MMM: ?DMNINMM$  $MMZ=MMM    DMM+                                                  
    ///          MMM~   $MM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       NMMN                                                        MMM?MMM~ ?MM8 MMM: ?DMNINMM$  $MMZ=MMM    DMM+                                                  
    ///          MMM~   $MM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       NMMN                                                        MMM?MMM~ ?MM8 MMM: ?DMNINMM$  $MMZ=MMM    DMM+                                                  
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       NMMN                                                        MMM?MMM~ ?MM8 MMM: ?DMNINMM$  $MMZ=MMM    DMM+                                                  
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       NMMN                                                        MMM?MMM~ ?MM8 MMM: ?DMNINMM$  $MMZ=MMM    DMM+                                                  
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM+                                                       NMMN                                                        MMM?MMM~ ?MM8 MMM: ?DMNINMM$  $MMZ=MMM    DMM+                                                  
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM+                                                       NMMN                                                        MMM?MMM~ ?MM8 MMM: ?DMNINMM$  $MMZ=MMM    DMM+                                                  
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM+                                                       NMMN                                                        MMM?MMM~ ?MM8 MMM: ?DMNINMM$  $MMZ=MMM    DMM+                                                  
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM+                                                       NMMN                                                        MMM?MMM~ ?MM8 MMM: ?DMNINMM$  $MMZ=MMM    DMM+                                                  
    ///          MMM~   $MM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM+                                                       NMMM                                                        MMM?MMM~ ?MM8 MMM: ?DMNINMM$  $MMZ=MMM    DMM+                                                  
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       NMMM                                                        MMM?MMM~ ?MM8 MMM: ?DMNINMM$  $MMZ=MMM    DMM+                                                  
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       NMMM                                                        MMM?MMM~ ?MM8 MMM: ?DMNINMM$  $MMZ=MMM    DMM+                                                  
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       NMMM                                                        MMM?MMM~ ?MM8 MMM: ?DMNINMM$  $MMZ=MMM    DMM+                                                  
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       MMMM                                                        MMM?MMM~ ?MM8 MMM: ?DMNINMM$  $MMZ=MMM    DMM+                                                  
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       MMMM                                                        MMM?MMM~ ?MM8 MMM: ?DMNINMM$  $MMZ=MMM    DMM+                                                  
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       MMMM                                                        MMM?MMM~ ?MM8 MMM: ?DMNINMM$  $MMZ=MMM    DMM+                                                  
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       MMMM                                                        MMM?MMM~ ?MM8 MMM: ?DMNINMM$  $MMZ=MMM    DMM+                                                  
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       MMMM                                                        MMM?MMM~ ?MM8 MMM: ?DMNINMM$  $MMZ=MMM    DMM+                                                  
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       MMMM                                                        MMM?MMM~ ?MM8 MMM: ?DMNINMM$  $MMZ=MMM    DMM+                                                  
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       MMMM                                                        MMM?MMM~ ?MM8 MMM: ?DMNINMM$  $MMZ=MMM    DMM+                                                  
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       MMMM                                                        MMM?MMM~ ?MM8 MMM: ?DMNINMM$  $MMZ=MMM    DMM+                                                  
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       MMMM                                                        MMM?MMM~ ?MM8 MMM: ?DMNINMM$  $MMZ=MMM    DMM+                                                  
    ///          MMM~   $MMI~MMN  7MMN:MMMI ,OMM+$MMO :MMM:NMM?                                                       MMMM                                                        MMM?MMM~ ?MM8 MMM: +8MNINMM7  $MMZ=MMM    DMM+                                                  
    ///          MMM~   ZMMI~MMD  IMMN,MMMI ,8MM+$MMO :MMM,NMM+                                                       MMMM                                                        MMM+MMM~ +MM8 MMM, ?DMNINMM$  $MM$=MMM    DMM+                                                  
    ///          MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+                                                  
    ///          MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:                                                 
    ///          MMM?=~=ZMMO7MMN=~$MMD?NMMO~?8MMI$MM8==MMM,DMM7=======================================================MMMMN,                                                      DMM$ZMM$: DMMI~MMN  IMMM?MMN   NMM++MMD   ,MMM,                                                 
    ///          MMM~   $MM7~MMD  7MMD:MMMI ,8MM?$MM8 ,MMM:DMM+                                                       MMMMN                                                       NMMZOMM7: OMM7~MMD  IMMM?MMN   NMM?+MMO    MMM,                                                 
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       MMMMD                                                       NMMZOMM$: 8MM7=MMD  IMMMIMMN   NMM??MMO    MMM,                                                 
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       MMMM8                                                       NMMZOMM$: 8MM7=MMD  IMMMIMMN   NMM??MMO    MMM,                                                 
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       MMMMO                                                       NMMZOMM$: 8MM7=MMD  IMMMIMMN   NMM??MMO    MMM,                                                 
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       MMMMO                                                       NMMZOMM$: 8MM7=MMD  IMMMIMMN   NMM??MMO    MMM,                                                 
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       MMMMO                                                       NMMZOMM$: 8MM7=MMD  IMMMIMMN   NMM??MMO    MMM,                                                 
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       MMMMO                                                       NMMZOMM$: 8MM7=MMD  IMMMIMMN   NMM??MMO    MMM,                                                 
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       NMMMO                                                       NMMZOMM$: 8MM7=MMD  IMMMIMMN   NMM??MMO    MMM,                                                 
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       NMMMO                                                       NMMZOMM$: 8MM7=MMD  IMMMIMMN   NMM??MMO    MMM,                                                 
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       NMMMO                                                       NMMZOMM$: 8MM7=MMD  IMMMIMMN   NMM??MMO    MMM,                                                 
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       NMMMO                                                       NMMZOMM$: 8MM7=MMD  IMMMIMMN   NMM??MMO    MMM,                                                 
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       NMMM$                                                       NMMZOMM$: 8MM7=MMD  IMMMIMMN   NMM??MMO    MMM,                                                 
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       NMMM$                                                       NMMZOMM$: 8MM7=MMD  IMMMIMMN   NMM??MMO    MMM,                                                 
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       NMMM$                                                       NMMZOMM$: 8MM7=MMD  IMMMIMMN   NMM??MMO    MMM,                                                 
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       MMMM$                                                       NMMZOMM$: 8MM7=MMD  IMMMIMMN   NMM??MMO    MMM,                                                 
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       NMMM$                                                       NMMZOMM$: 8MM7=MMD  IMMMIMMN   NMM??MMO    MMM,                                                 
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       NMMM$                                                       NMMZOMM$: 8MM7=MMD  IMMMIMMN   NMM??MMO    MMM,                                                 
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       NMMM$                                                       NMMZOMM$: 8MM7=MMD  IMMMIMMN   NMM??MMO    MMM,                                                 
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       NMMM$                                                       NMMZOMM$: 8MM7=MMD  IMMMIMMN   NMM??MMO    MMM,                                                 
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       NMMM7                                                       NMMZOMM$: 8MM7=MMD  IMMMIMMN   NMM??MMO    MMM,                                                 
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       NMMMI                                                       NMMZOMM$: 8MM7=MMD  IMMMIMMN   NMM??MMO    MMM,                                                 
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       NMMMI                                                       NMMZOMM$: 8MM7=MMD  IMMMIMMN   NMM??MMO    MMM,                                                 
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       NMMMI                                                       NMMZOMM$: 8MM7=MMD  IMMMIMMN   NMM??MMO    MMM,                                                 
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       NMMMI                                                       NMMZOMM$: 8MM7=MMD  IMMMIMMN   NMM??MMO    MMM,                                                 
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       NMMMI                                                       NMMZOMM$: 8MM7=MMD  IMMMIMMN   NMM??MMO    MMM,                                                 
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       NMMMI                                                       NMMZOMM$: 8MM7=MMD  IMMMIMMN   NMM??MMO    MMM,                                                 
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       NMMM7                                                       NMMZOMM$: 8MM7=MMD  IMMMIMMN   NMM??MMO    MMM,                                                 
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       NMMM?                                                       NMMZOMM$: 8MM7=MMD  IMMMIMMN   NMM??MMO    MMM,                                                 
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       NMMM?                                                       NMMZOMM$: 8MM7=MMD  IMMMIMMN   NMM??MMO    MMM,                                                 
    ///          MMM~   ZMM7~MMN  7MMN,MMMI ,OMM+$MMO :MMM,DMM?                                                       NMMM?                                                       NMMZOMM$: 8MM7=MMD  IMMMIMMN   NMM??MMO    MMM,                                                 
    ///          MMM?=~~8MM$?MMN~=ZMMN=MMM7==DMMIOMM8~+MMM=NMM7~=========~~:                                          NMMM?                                           ============MMMDNMMZ+~DMM8ZMMN~=$MMM8MMM~=~MMMOOMM8~=~~MMM:                                                 
    ///          8DMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMI:                                         NMMM?                                         ~=MMMMDMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDD,                                                 
    ///           IMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:                                        NMMM?                                        =MMMMMMDMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM?                                                   
    ///                                                                  =MMM:                                        NMMM?                                        =MMN                                                                                                           
    ///                                                                  =MMM:                                        NMMM+                                        =MMN                                                                                                           
    ///                                                                  =MMM:                                        NMMM+                                        =MMN                                                                                                           
    ///                                                                  =MMM:                                        NMMM=                                        =MMN                                                                                                           
    ///                                                                  =MMM:                                        NMMM=                                        =MMN                                                                                                           
    ///                                                                  =MMM:                                        NMMM=                                        =MMN                                                                                                           
    ///                                                                  =MMM:                                        NMMM=                                        =MMN                                                                                                           
    ///                                                                  =MMM:                                        DMMM=                                        =MMN                                                                                                           
    ///                                                                  =MMM:                                        DMMM=                                        =MMN                                                                                                           
    ///                                                                  =MMM:                                        DMMM=                                        =MMN                                                                                                           
    ///                                                                  =MMM:                                        DMMM~                                        =MMN                                                                                                           
    ///                                                                  =MMM:                                        DMMM:                                        =MMN                                                                                                           
    ///                                                                  =MMM:                                        DMMM,                                        =MMN                                                                                                           
    ///                                                                  =MMM:                                        DMMM,                                        =MMN                                                                                                           
    ///                                                                  =MMM:                                        DMMM,                                        =MMN                                                                                                           
    ///                                                                  =MMM:                                        8MMM,                                        =MMN                                                                                                           
    ///                                                                  =MMM:                                        8MMM:                                        =MMN                                                                                                           
    ///                                                                  =MMM:                                        OMMM:                                        ~MMN                                                                                                           
    ///                                                                  =MMM8OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOMMMMOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO8MMD                                                                                                           
    ///                                                                  :I8MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN?                                                                                                           
    ///                                                                    +ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ$~ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ$                                                                                                            
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    ///                                                                                                                                                                                                                                                                           
    

    [DebuggerDisplay("Base Point = {BasePoint}")]    
    public class Solid
    {
        /// <summary>
        /// Accesses a point on the solid 
        /// </summary>
        public Point PointOnSolid
        {
            get
            {
                Point returnPoint = null;
                if (_planeRegions.Count > 0)
                {
                    returnPoint = _planeRegions[0].BasePoint;
                }
                return returnPoint;
            }
        }


        public Point CenterPoint()
        {
            throw new NotImplementedException();
        }

        public Line MidLine()
        {
            throw new NotImplementedException();
        }

        public List<PlaneRegion> PlaneRegions
        {
            get { return _planeRegions; }
            set { _planeRegions = value; }
        }
        private List<PlaneRegion> _planeRegions;

        public Solid()
        {
            _planeRegions = new List<PlaneRegion>();
        }

        public Solid(List<LineSegment> passedLineSegments)
        {
            _planeRegions = passedLineSegments.MakeCoplanarLineSegmentsIntoRegions();
        }

        public Solid(List<PlaneRegion> passedPlaneRegions)
        {
            _planeRegions = new List<PlaneRegion>(passedPlaneRegions);
        }

        public Solid(Solid passedSolid)
        {
            _planeRegions = passedSolid._planeRegions;
        }

        public List<LineSegment> LineSegments
        {
            get
            {
                List<LineSegment> returnList = new List<LineSegment>();

                foreach (PlaneRegion region in _planeRegions)
                {
                    if (region.PlaneBoundaries != null)
                        returnList.AddRange(region.PlaneBoundaries);
                }

                return returnList;
            }
            set
            {
                this._planeRegions = value.MakeCoplanarLineSegmentsIntoRegions();
            }
        }

        /// <summary>
        /// Shifts the solid to another location and orientation
        /// </summary>
        /// <param name="passedShift"></param>
        /// <param name="passedRotationAxis"></param>
        public Solid Shift(Shift passedShift)
        {
            List<PlaneRegion> shiftedRegions = new List<PlaneRegion>( _planeRegions.Shift(passedShift));

            return new Solid(shiftedRegions);
        }
    }
}
